### ISSUE TITLE
key error "state['best_step']"  line 160 in train.py

### ISSUE THREAD

**Issue by cw9000** [TooTouch/MemSeg#1]
when running main.py with a yaml config it finishes with an error
I believe it is an easy fix.  on line 156 just change it to this:
state.update({'latest_step':step})

**Comment by tootouch** [comment]
Hi, @cw9000 

Thank you for letting me know. 
I fix it.

https://github.com/TooTouch/MemSeg/commit/f4f625964dff3c77c678402bf328b9326fdcc165

https://github.com/TooTouch/MemSeg/blob/f4f625964dff3c77c678402bf328b9326fdcc165/train.py#L152-L161
