### ISSUE TITLE
What is pixel/image AUROC?

### ISSUE THREAD

**Issue by TorAP** [TooTouch/MemSeg#13]
I am having troubles understanding this metric. 

As normally auroc curves are related to TPR (true positive rate) and FPR (false positive rate) for each classification threshhold value. But in this example we get a point on the auroc curve for every 100th step, what exactly is a point?  e.g., how should I interpret 0.84 pixel-level AUC-ROC
<img width="423" alt="Screenshot 2023-05-03 at 00 01 32" src="https://user-images.githubusercontent.com/46317353/235795442-3a57d120-2ebb-4004-bf2e-00885c11b160.png">

**Comment by tootouch** [comment]
Hi, @TorAP 

The point is a AUPRO value which is calculated after 100th **training** step.

The answer for the interpretation  is here https://github.com/TooTouch/MemSeg/issues/6.
