### ISSUE TITLE
A question about Datasets

### ISSUE THREAD

**Issue by ztk985** [TooTouch/MemSeg#19]
Hello author, thank you for providing the project code. But I would like to ask you, how should I prepare the data set before training the model

**Comment by roberto722** [comment]
Up

**Comment by jamdodot** [comment]
same question
self.target  need to be set, such as bottle?

**Comment by tootouch** [comment]
@ztk985 @roberto722 

I'm sorry too late.
You can download MVTecAD datasets in [here](https://www.mvtec.com/company/research/datasets/mvtec-ad).

**Comment by tootouch** [comment]
@jamdodot 

Yes. 
If you want to train a model for bottle class, you need to set the target as bottle. 
```bash
python main.py --yaml_config ./configs.yaml DATASET.target capsule
```

**Comment by jamdodot** [comment]
> @jamdodot
> 
> Yes. If you want to train a model for bottle class, you need to set the target as bottle.
> 
> ```shell
> python main.py --yaml_config ./configs.yaml DATASET.target capsule
> ```
I also want to ask [example] model overview.ipynb. Is this file the inference process? Is it using a trained model?

**Comment by tootouch** [comment]
@jamdodot 

`[example] model overview.ipynb` is a tutorial example for one batch of training dataset.
The purpose of the notebook file is to check the process of the MemSeg.

**Comment by jamdodot** [comment]
Hello, sorry to bother you. How can i set up training and testing on other datasets. such as _KolektorSDD_  &  _ELPV_
