### ISSUE TITLE
add model.eval() to Inference code

### ISSUE THREAD

**Issue by sonkt98** [TooTouch/MemSeg#21]
Hi
First, thank you for the great implementation.
It works very well on mvtec and my custom dataset. It achieves high score and create pretty good results.

I made test.py to test my model. Model's output was pretty good, but output from test.py was different from that of inference.ipynb.
Model and Input data was same, so I compared two file. Than I found that, because there is no "model.eval()" in inference.ipynb,  model in inference.ipynb was producing wrong result. After I added "model.eval()", two file produced same result.

I think, "model.eval()" should be added to inference.ipynb.

**Comment by tootouch** [comment]
Hi, @sonkt98 

Thank you for pointing out. 
I add `model.eval()` in inference.ipynb.

best regards,
