### ISSUE TITLE
缺陷检测交流微信群，互相交流学习进步

### ISSUE THREAD

**Issue by RuojiWang** [TooTouch/MemSeg#25]
缺陷检测交流微信群，互相交流学习进步

![20240108092627](https://github.com/TooTouch/MemSeg/assets/14054362/cc659281-919c-4cc8-a8c9-b9570fd13c87)

**Comment by kimsax** [comment]
有新的二维码吗，

**Comment by kimsax** [comment]
> 缺陷检测交流微信群，互相交流学习进步
> 
> ![20240108092627](https://private-user-images.githubusercontent.com/14054362/294798259-cc659281-919c-4cc8-a8c9-b9570fd13c87.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MDY1NzQsIm5iZiI6MTcxMjQwNjI3NCwicGF0aCI6Ii8xNDA1NDM2Mi8yOTQ3OTgyNTktY2M2NTkyODEtOTE5Yy00Y2M4LWE4YzktYjk1NzBmZDEzYzg3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDEyMjQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjZjliN2YyOGZhMTU2OTJmMjkxZmRiNzQzNzFkMTEwYWVmNTQyZjAyMDQxNjQ3ZmY0OWE3ZGRlYWRhZGY0MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6lC56_j1xNEMGrcM92_j0xac63wwcsNiiM0AWmFqwJw)

新二维码有吗

**Comment by RuojiWang** [comment]
> > 缺陷检测交流微信群，互相交流学习进步
> > ![20240108092627](https://private-user-images.githubusercontent.com/14054362/294798259-cc659281-919c-4cc8-a8c9-b9570fd13c87.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MDY1NzQsIm5iZiI6MTcxMjQwNjI3NCwicGF0aCI6Ii8xNDA1NDM2Mi8yOTQ3OTgyNTktY2M2NTkyODEtOTE5Yy00Y2M4LWE4YzktYjk1NzBmZDEzYzg3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDEyMjQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjZjliN2YyOGZhMTU2OTJmMjkxZmRiNzQzNzFkMTEwYWVmNTQyZjAyMDQxNjQ3ZmY0OWE3ZGRlYWRhZGY0MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6lC56_j1xNEMGrcM92_j0xac63wwcsNiiM0AWmFqwJw)
> 
> 新二维码有吗

有的，我重新发一份
![微信图片_20240407121310](https://github.com/TooTouch/MemSeg/assets/14054362/151c69e7-0bae-4fd3-ba6a-fe44020b9597)

**Comment by liuaohunter** [comment]
还有群吗
