### ISSUE TITLE
run the “python main.py configs=configs.yaml DATASET.target=bottle” command always wrong cause by datasets

### ISSUE THREAD

**Issue by philchenup** [TooTouch/MemSeg#27]
now, i prepare the dataset/dtd/images file and dataset/MVTec file,the dataset/MVTec have bottle,tile,carpet,cable and so on data download from MVTec web。but always wrong when run the command "python main.py configs=configs.yaml DATASET.target=bottle"（ValueError: num_samples should be a positive integer value, but got num_samples=0）, where need to correct in the code, in configs.yaml, i change the "target=bottle",any other need to correct? so complicated.

**Comment by shellxiao** [comment]
@philchenup same error. how did you solve it?

**Comment by liuaohunter** [comment]
请问怎么解决的
