### ISSUE TITLE
DefaultCPUAllocator: not enough memory: you tried to allocate 223045988 bytes.

### ISSUE THREAD

**Issue by fhf526** [TooTouch/MemSeg#3]
Hello,
           when I trained to 600 iterations, prompted this error, I want to ask what is the reason.The training parameters are based on the configuration file. I only changed nb _ memory _ sample to 40, and the rest did not change.

Looking forward to your answer.

**Comment by tootouch** [comment]
Hi, @fhf526 

The error message points out that you are running out of RAM.

**Comment by fhf526** [comment]
> 嗨，@fhf526
> 
> 错误消息指出您的 RAM 不足。

I found that when using the evaluation function, there is no reset, which will cause the memory to increase. I added a reset in the next few lines to solve the problem.
In the train.py file under the evaluate function:
   `auroc_image_metric.reset()
    auroc_pixel_metric.reset()
    aupro_pixel_metric.reset()`

**Comment by tootouch** [comment]
Thank you for sharing the solution.

I update evaluate function https://github.com/TooTouch/MemSeg/commit/243046c412643f8580661fe98a21c51a6cb1930d.
