### ISSUE TITLE
about [demo] model inference.ipynb

### ISSUE THREAD

**Issue by Smallwhite999** [TooTouch/MemSeg#30]
The amount of tensor stored in Memory is inconsistent, resulting in inconsistent input and output results, but the training and testing are normal. Visualization will always report an error. How can I solve it?

![图片](https://github.com/TooTouch/MemSeg/assets/56509992/a9fd6f13-97a0-4c85-b310-8415b7ae27bc)

**Comment by tootouch** [comment]
@Smallwhite999 

I think that the error is caused by the image size. I used an image size 256 x 256. And the MemSeg is constructed to fit the image size. 

If you used different image size, you have to adjust MemSeg's architecture.
