### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by li038** [TooTouch/MemSeg#31]
Do you have a great god who knows how to solve this problem？

 File "F:\MemSeg-main\models\memory_module.py", line 33, in update
    input_normal, _, _ = self.normal_dataset[samples_idx[i]]
                                             ~~~~~~~~~~~^^^

**Comment by tootouch** [comment]
@A0401A 

If you defined `self.normal_dataset` as `MemSegDataset` class in data folder, `self.normal_dataset` should return `img`, `mask`, and `target`  as follows

https://github.com/TooTouch/MemSeg/blob/7e3a8b897b0b0cdafd3b800be5437180bef2c36a/data/dataset.py#L126

Did you use your custom dataset, not `MemSegDataset`?

**Comment by li038** [comment]
Thank you for your reply. I am using MemSegDataset, and I added a dot before the dataset path to avoid any errors.
