### ISSUE TITLE
How do I train my own data set

### ISSUE THREAD

**Issue by wooderntower** [TooTouch/MemSeg#32]

**Comment by tootouch** [comment]
@wooderntower 

If you set your dataset to be the same as the MVTec dataset directory settings, you can use the dataset to train MemSeg.

**Comment by wooderntower** [comment]
I re-annotated the original data set and a new error occurred.
ValueError：Only one class present in y_true. ROC AUC score is not defined in that case.

**Comment by wooderntower** [comment]
Thanks to the guidance, I succeeded.
