### ISSUE TITLE
requirements specific versions

### ISSUE THREAD

**Issue by alexandre2r** [TooTouch/MemSeg#4]
Hi @TooTouch , thanks for the work! I was trying to do some little experimentation with your repo but I am not able to fulfill the versions needed in `requirements.txt`. 
Does anyone have the specific versions? Thanks in advance.

A little typo in the `opencv` requirement:
```txt
anomalib
opencv-python
einops
timm
wandb
```

**Comment by tootouch** [comment]
Hi, @alexandre2r 

Thank you for correcting the typo.
I added the specific versions in `requirements.txt`

```
anomalib==0.3.7
opencv-python==4.6.0
einops==0.5.0
timm==0.5.4
wandb==0.12.17
```

best regards,
