### ISSUE TITLE
怎样做一个预测?

### ISSUE THREAD

**Issue by luohao136486939** [TooTouch/MemSeg#6]
大佬，您好！我怎样预测一张图片是否异常，可以直接使用 AUCROC-image的值来判断么？

**Comment by zj0118** [comment]
请问您运行成功了嘛

**Comment by tootouch** [comment]
Hi, @luohao136486939 

Whether or not to determine the anomaly of the image is determined by a threshold based on the anomaly score of the image.

AUROC is the threshold independent metrics. If you determine the anomaly of the image, use the anomaly score of the image. The image- and pixel-level anomaly score is calculated as mentioned in MemSeg paper.

"MemSeg obtains the anomaly score for each pixel in the image in an end-to-end manner, and the mean of the scores of the top 100 most abnormal pixel points in the image is used as the anomaly score at the image-level"

Best regards,
