### ISSUE TITLE
why we need to move memory bank to CPU while inference time?

### ISSUE THREAD

**Issue by prajyotmorey** [TooTouch/MemSeg#7]
Hii @TooTouch, In inference code, you have moved the memory bank to the CPU? is it necessary? Does it have any advantage to doing so? I want to run memsem on GPU, so what will be the best choice for it?

![image](https://user-images.githubusercontent.com/30291763/221007514-7f71de7b-acbe-4470-8cd7-15052cf36c4b.png)

**Comment by tootouch** [comment]
Hi, @prajyotmorey 

If you want to use GPU, you can change device into gpu.

Best regards,
