### ISSUE TITLE
The code does not run

### ISSUE THREAD

**Issue by zj0118** [TooTouch/MemSeg#8]
![1677571228984](https://user-images.githubusercontent.com/64900013/221790243-34aefc5e-3dcb-44f8-96ab-9e63562a256e.png)
How should I fix it？

**Comment by tootouch** [comment]
Hi, @zj0118 

Can you explain under what circumstances the error occurred?

**Comment by EudicL** [comment]
I think the mistake is because the wrong image path was loaded.

**Comment by liuaohunter** [comment]
我也遇到了这个错误，请问怎么解决的
